### ISSUE TITLE
Use mp4v encoding instead of h264

### ISSUE THREAD

**Issue by raphajaner** [theRealProHacker/PyGameRecorder#3]
Hi @theRealProHacker ,

Using h264 as a codec for mp4 causes issues on many platforms since it falls under a GPL license ([see](https://github.com/opencv/opencv-python/issues/207)) but is used in this library:
https://github.com/theRealProHacker/PyGameRecorder/blob/97551c66c3a5eaa1b9c30527f9139699d32e9c8f/src/pygame_screen_record/ScreenRecorder.py#L439-L440
You actually refer to [StackOverflow](https://stackoverflow.com/a/55596396/15046005 ) where they suggest using `mp4v` instead. Is there a reason you decided to use `"h264"`? Otherwise, I guess using `"mp4v"`  would be the better choice :)
```python
codec_dict = {"avi": "DIVX", "webm": "WEBM", "mp4": "mp4v"}
```

**Comment by theRealProHacker** [comment]
Hi, thanks for raising this issue. I actually linked the SO answer because it says at the bottom that web browsers (only) support `h264` and I felt like this would be a good reason to prefer it over `mp4v`. 

But I also made `codec_dict` publicly/globally available and mutable on purpose, so that users can alter it for their needs and use the codec they prefer the most. I think that's even mentioned somewhere in the README. So the easiest work-around is simply doing `codec_dict["mp4"]="mp4v"` (or whatever `FOURCC` you like) before you save any recording. 

What I really want, is FFmpeg to select the optimal codec automatically from the file extension. It should be possible, but I don't know how to do it. 

For that reason, `h264` might be a good alternative.  
`mp4v` will always work, but the product might not be displayable everywhere (from my experience). With `h264` it will most likely not work, but it's always more optimal.  
Either it just works or it doesn't and FFmpeg chooses the next best alternative automatically. The bad console byproduct is irrelevant in most pygame applications (pygame produces it anyway).

I don't think there are any licensing problems by simply referring to the codec, right?
I'll leave this issue open, until everything is documented that should be documented.

If you have any further questions or suggestions, It'd be a pleasure to listen to your valuable insights.

**Comment by raphajaner** [comment]
Thanks for your detailed answer!! No there shouldn't be any issues by only referring to it.

I feel like the readme is a tiny bit involved, so finding such information can be difficult.  Maybe a troubleshooting section discussing such things could be helpful for others in the future :)
