### ISSUE TITLE
Recording the game at game FPS speed

### ISSUE THREAD

**Issue by valpaz** [theRealProHacker/PyGameRecorder#6]
Hey,

This is working perfectly fine but i was asking myself if it was possible to record my game at game FPS. My game is more of a simulation running several hours and sometimes it drop low on FPS because of appening events making sprite spiking in number.

Thank you in advance for your answer !

**Comment by theRealProHacker** [comment]
Hi,

thanks for raising this issue. However, I think I do not exactly understand what is happening.

Do you mean that your game drops FPS and you want to record at that FPS, or does the recorder drop FPS and you want it to definitely get every frame of your simulation?

As a tip, if your program isn't a game in such, you might be able to lower the FPS, which will likely lead to a smoother performance.

Apart from that, you should probably not record several hours all at once. This is because this recorder doesn't stream to the disk but holds everything in memory instead.  

I hope I could help you 😁

**Comment by valpaz** [comment]
Hey, thanks for your quick answer and advise !

Yes my game drops FPS and i want to record a that FPS. 
Like if my game/simulation is at 30 fps in "normal" moment, i want the recorder to record at lets say 30 fps, but if the simulation drop in fps, i want the recorder to keep recording at 30 FPS. So in theory, if my game drop for a minute at 15 fps, the recorder will schrink 2s in 1s to keep the final result smooth. I dont know if it is comprehensible.

Thanks for the help :D

**Comment by theRealProHacker** [comment]
I don't think it's possible out-of-the box or with just a line of code. But you can manipulate the recordings manually afterward by removing or adding frames or splitting the recordings and changing the fps of those recordings individually.

Maybe you could also reach into the recorder thread and use a barrier or a similar synchronization method, but I really don't know.

**Comment by theRealProHacker** [comment]
@valpaz 

Actually, I just thought about this again randomly. Maybe try something like this if you dare (memory-wise).

```py
frames = []
while True:
 # your drawing code
 frames.append(screen.copy())
recording = Recording(30, frames[0].get_size(), 0)
```

Now you can save the recording in whatever way you want to
